apiVersion: 1

policies:
  - orgId: 1
    receiver: telegram-egr
    group_by:
      - alertname
    group_wait: 30s
    group_interval: 5m
    # Напоминать о всё ещё активном алерте раз в 4 часа
    repeat_interval: 4h
